import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Home(),
        ]),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 63,
                  decoration: BoxDecoration(color: Color(0xFF706E6E)),
                ),
              ),
              Positioned(
                left: 95,
                top: 19,
                child: Text(
                  'Events',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Kavoon',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 13,
                child: Container(
                  width: 61,
                  height: 31,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/61x31"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 94,
                child: Text(
                  'Live',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 274,
                top: 94,
                child: Text(
                  'Past',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 139,
                top: 94,
                child: Text(
                  'Upcoming',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 14,
                top: 120,
                child: Container(
                  width: 81.50,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFFF3E01),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 14,
                top: 131,
                child: Container(
                  width: 324,
                  height: 75,
                  decoration: BoxDecoration(color: Color(0xFFF5F4F4)),
                ),
              ),
              Positioned(
                left: 14,
                top: 131,
                child: Container(
                  width: 107,
                  height: 75,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/107x75"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 139,
                top: 169,
                child: SizedBox(
                  width: 177,
                  child: Text(
                    'Sat 25 may 2024, 1500hrs - 2100hrs',
                    style: TextStyle(
                      color: Color(0xFFFF3D00),
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 14,
                top: 217,
                child: Container(
                  width: 324,
                  height: 75,
                  decoration: BoxDecoration(color: Color(0xFFF5F4F4)),
                ),
              ),
              Positioned(
                left: 14,
                top: 217,
                child: Container(
                  width: 107,
                  height: 75,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/107x75"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 139,
                top: 229,
                child: SizedBox(
                  width: 183,
                  child: Text(
                    'Kitchen Cooking Competition',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kavoon',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 139,
                top: 255,
                child: SizedBox(
                  width: 177,
                  child: Text(
                    'Sat 25 may 2024, 1500hrs - 2100hrs',
                    style: TextStyle(
                      color: Color(0xFFFF3D00),
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 303,
                child: Container(
                  width: 324,
                  height: 75,
                  decoration: BoxDecoration(color: Color(0xFFF5F4F4)),
                ),
              ),
              Positioned(
                left: 15,
                top: 303,
                child: Container(
                  width: 107,
                  height: 75,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/107x75"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 140,
                top: 315,
                child: SizedBox(
                  width: 183,
                  child: Text(
                    'Kitchen Cooking Competition',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kavoon',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 140,
                top: 341,
                child: SizedBox(
                  width: 177,
                  child: Text(
                    'Sat 25 may 2024, 1500hrs - 2100hrs',
                    style: TextStyle(
                      color: Color(0xFFFF3D00),
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 257,
                top: 693,
                child: Container(
                  width: 75,
                  height: 75,
                  decoration: ShapeDecoration(
                    color: Color(0xFF706E6E),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 257,
                top: 693,
                child: Container(
                  width: 75,
                  height: 75,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/75x75"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}