import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AndroidLarge16(),
        ]),
      ),
    );
  }
}

class AndroidLarge16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 63,
                  decoration: BoxDecoration(color: Color(0xFF706E6E)),
                ),
              ),
              Positioned(
                left: 70,
                top: 19,
                child: Text(
                  'Events Summary',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Kavoon',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 13,
                child: Container(
                  width: 61,
                  height: 31,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/61x31"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 63,
                child: Container(
                  width: 360,
                  height: 219,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 14,
                top: 294,
                child: Container(
                  width: 335,
                  height: 91,
                  decoration: BoxDecoration(
                    color: Color(0xFFF4F4F4),
                    border: Border(
                      left: BorderSide(width: 4, color: Color(0xFFFF3D00)),
                      top: BorderSide(color: Color(0xFFFF3D00)),
                      right: BorderSide(color: Color(0xFFFF3D00)),
                      bottom: BorderSide(color: Color(0xFFFF3D00)),
                    ),
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 12,
                top: 398,
                child: Container(
                  width: 335,
                  height: 53,
                  decoration: BoxDecoration(
                    color: Color(0xFFF4F4F4),
                    border: Border(
                      left: BorderSide(width: 4, color: Color(0xFFFF3D00)),
                      top: BorderSide(color: Color(0xFFFF3D00)),
                      right: BorderSide(color: Color(0xFFFF3D00)),
                      bottom: BorderSide(color: Color(0xFFFF3D00)),
                    ),
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 12,
                top: 464,
                child: Container(
                  width: 334,
                  height: 327,
                  decoration: BoxDecoration(
                    color: Color(0xFFF9F9F9),
                    border: Border(
                      left: BorderSide(width: 4, color: Color(0xFFFF3D00)),
                      top: BorderSide(color: Color(0xFFFF3D00)),
                      right: BorderSide(color: Color(0xFFFF3D00)),
                      bottom: BorderSide(color: Color(0xFFFF3D00)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 314,
                child: Text(
                  'Amount Collected',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 348,
                child: Text(
                  'Amount Payable',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 502,
                child: Text(
                  'Close Ticket Sales',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w800,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 52,
                top: 548,
                child: Container(
                  width: 253,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF1F1F1),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 52,
                top: 606,
                child: Container(
                  width: 253,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF1F1F1),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 52,
                top: 666,
                child: Container(
                  width: 253,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF1F1F1),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 666,
                child: Container(
                  width: 72,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFD4C00),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 604,
                child: Container(
                  width: 72,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFD4C00),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 548,
                child: Container(
                  width: 72,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFD4C00),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 72,
                top: 562,
                child: Text(
                  'Early Bird',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Kavoon',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 78,
                top: 623,
                child: Text(
                  'Regular',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Kavoon',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 679,
                child: Text(
                  'VIP',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Kavoon',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 203,
                top: 314,
                child: Text(
                  'Ksh 3,0000,000',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 203,
                top: 348,
                child: Text(
                  'Ksh 2,7000,000',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 236,
                top: 553,
                child: SizedBox(
                  width: 69,
                  height: 33,
                  child: Text(
                    'Close',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 236,
                top: 671,
                child: SizedBox(
                  width: 69,
                  height: 33,
                  child: Text(
                    'Close',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 236,
                top: 609,
                child: SizedBox(
                  width: 69,
                  height: 33,
                  child: Text(
                    'Close',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 418,
                child: Text(
                  'Tickets and Check IN',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 284,
                top: 410,
                child: Container(
                  width: 42,
                  height: 31,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/42x31"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -3,
                top: 63,
                child: Container(
                  width: 363,
                  height: 219,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 35.32,
                        top: 180.67,
                        child: Container(
                          height: 32.32,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 38.45,
                                top: 0,
                                child: Container(
                                  width: 248.07,
                                  height: 32.32,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 4.35,
                                          height: 32.32,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 15.90,
                                                child: SizedBox(
                                                  width: 4.35,
                                                  height: 16.42,
                                                  child: Text(
                                                    '0',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 12,
                                                      fontFamily: 'Inter',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 81.78,
                                        top: 0,
                                        child: Container(
                                          width: 3.26,
                                          height: 32.32,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 15.90,
                                                child: SizedBox(
                                                  width: 3.26,
                                                  height: 16.42,
                                                  child: Text(
                                                    '1',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 12,
                                                      fontFamily: 'Inter',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 162.48,
                                        top: 0,
                                        child: Container(
                                          width: 4.35,
                                          height: 32.32,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 15.90,
                                                child: SizedBox(
                                                  width: 4.35,
                                                  height: 16.42,
                                                  child: Text(
                                                    '2',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 12,
                                                      fontFamily: 'Inter',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 243.72,
                                        top: 0,
                                        child: Container(
                                          width: 4.35,
                                          height: 32.32,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 15.90,
                                                child: SizedBox(
                                                  width: 4.35,
                                                  height: 16.42,
                                                  child: Text(
                                                    '3',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 12,
                                                      fontFamily: 'Inter',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 13.59,
                        top: 1.60,
                        child: Container(
                          width: 21.74,
                          height: 187.03,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 21.74,
                                  height: 187.03,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 11.41,
                                        top: 170.60,
                                        child: Container(
                                          width: 10.32,
                                          height: 16.42,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: SizedBox(
                                                  width: 4.35,
                                                  height: 16.42,
                                                  child: Text(
                                                    '0',
                                                    textAlign: TextAlign.right,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 12,
                                                      fontFamily: 'Inter',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 3.26,
                                        top: 126.80,
                                        child: Container(
                                          width: 18.48,
                                          height: 49.28,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: SizedBox(
                                                  width: 12.50,
                                                  height: 49.28,
                                                  child: Text(
                                                    '250',
                                                    textAlign: TextAlign.right,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 12,
                                                      fontFamily: 'Inter',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 3.26,
                                        top: 83,
                                        child: Container(
                                          width: 18.48,
                                          height: 49.28,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: SizedBox(
                                                  width: 12.50,
                                                  height: 49.28,
                                                  child: Text(
                                                    '500',
                                                    textAlign: TextAlign.right,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 12,
                                                      fontFamily: 'Inter',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 3.80,
                                        top: 39.20,
                                        child: Container(
                                          width: 17.93,
                                          height: 49.28,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: SizedBox(
                                                  width: 11.96,
                                                  height: 49.28,
                                                  child: Text(
                                                    '750',
                                                    textAlign: TextAlign.right,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 12,
                                                      fontFamily: 'Inter',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 21.74,
                                          height: 32.85,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: SizedBox(
                                                  width: 15.76,
                                                  height: 32.85,
                                                  child: Text(
                                                    '1000',
                                                    textAlign: TextAlign.right,
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 12,
                                                      fontFamily: 'Inter',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 35.32,
                        top: 5.48,
                        child: Container(
                          width: 324.96,
                          height: 175.20,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 324.96,
                                  height: 175.20,
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 324.96,
                                  height: 175.20,
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 43.45,
                        top: 5.65,
                        child: Container(
                          width: 308.39,
                          height: 175.02,
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 3,
                        top: 219,
                        child: Container(
                          width: 360,
                          height: 102.62,
                          decoration: BoxDecoration(color: Color(0xFF464646)),
                        ),
                      ),
                      Positioned(
                        left: 3,
                        top: 215.83,
                        child: Container(
                          width: 357,
                          height: 125.90,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 3,
                        top: 215.83,
                        child: Container(
                          width: 360,
                          height: 125.90,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
