import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AndroidLarge17(),
        ]),
      ),
    );
  }
}

class AndroidLarge17 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 63,
                  decoration: BoxDecoration(color: Color(0xFF706E6E)),
                ),
              ),
              Positioned(
                left: 77,
                top: 19,
                child: Text(
                  'Events CheckIn ',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Kavoon',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 13,
                child: Container(
                  width: 61,
                  height: 31,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/61x31"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 275,
                top: 4,
                child: Container(
                  width: 59,
                  height: 50,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/59x50"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 119,
                child: Container(
                  width: 307,
                  height: 602,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 27,
                top: 119,
                child: Container(
                  width: 307,
                  height: 602,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(6)),
                    shadows: [
                      BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 1,
                      ),
                      BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 6,
                        offset: Offset(0, 4),
                        spreadRadius: -1,
                      ),
                      BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 4,
                        offset: Offset(0, 2),
                        spreadRadius: -2,
                      )
                    ],
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: double.infinity,
                        height: 72,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(color: Color(0xFFF1F5F9)),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Expanded(
                              child: Container(
                                height: 73,
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 32, vertical: 16),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(
                                  border: Border(
                                    left: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    top: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    right: BorderSide(
                                      width: 1,
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    bottom: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                  ),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    SizedBox(
                                      width: 65,
                                      height: 57,
                                      child: Text(
                                        'Email Address',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w700,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                height: 72,
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 32, vertical: 16),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(
                                  border: Border(
                                    left: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    top: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    right: BorderSide(
                                      width: 1,
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    bottom: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                  ),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    SizedBox(
                                      width: 45,
                                      child: Text(
                                        'Ticket',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w700,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                height: 80,
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 32, vertical: 16),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(
                                  border: Border(
                                    left: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    top: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    right: BorderSide(
                                      width: 1,
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    bottom: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                  ),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    SizedBox(
                                      width: 60,
                                      height: 48,
                                      child: Text(
                                        'Amount ',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w700,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                height: 47,
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 32, vertical: 16),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(
                                  border: Border(
                                    left: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    top: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    right: BorderSide(
                                      width: 1,
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    bottom: BorderSide(
                                      strokeAlign:
                                          BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                  ),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    SizedBox(
                                      width: 46,
                                      child: Text(
                                        'Action',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w700,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        height: 490,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(color: Colors.white),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 62,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 62,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 58,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 47,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 47,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign:
                                                BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
