import 'package:flutter/material.dart';
import 'package:tikiti/add-event.dart';
import 'package:tikiti/admin-index.dart';
import 'package:tikiti/login.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Ticket(),
        ]),
      ),
    );
  }
}

class Ticket extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Events CheckIn'),
        backgroundColor: Colors.grey[700],
      ),
      drawer: Drawer(
        child: Column(
          children: [
            Container(
              width: 360,
              height: 800,
              clipBehavior: Clip.antiAlias,
              decoration: const BoxDecoration(color: Colors.white),
              child: Stack(
                children: [
                  Positioned(
                    left: 0,
                    top: 0,
                    child: Container(
                      width: 236,
                      height: 800,
                      decoration: const BoxDecoration(color: Color(0xFF626262)),
                    ),
                  ),
                  Positioned(
                    left: 0,
                    top: 0,
                    child: Container(
                      width: 236,
                      height: 154,
                      decoration: const BoxDecoration(color: Color(0xFFF4F4F4)),
                    ),
                  ),
                    Positioned(
                    left: 74,
                    top: 185,
                    child: GestureDetector(
                      onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => Home()),
                      );
                      },
                      child: const SizedBox(
                      width: 49,
                      child: Text(
                        'Events',
                        style: TextStyle(
                        color: Colors.black,
                        fontSize: 12,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w700,
                        height: 1,
                        ),
                      ),
                      ),
                    ),
                    ),
                    Positioned(
                    left: 74,
                    top: 231,
                    child: GestureDetector(
                      onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => AddEvent()),
                      );
                      },
                      child: const SizedBox(
                      width: 98,
                      child: Text(
                        'Create Event',
                        style: TextStyle(
                        color: Colors.black,
                        fontSize: 12,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w700,
                        height: 1,
                        ),
                      ),
                      ),
                    ),
                    ),
                    Positioned(
                      left: 74,
                      top: 277,
                      child: GestureDetector(
                        onTap: () {
                          Navigator.push(
                            context,
                            MaterialPageRoute(builder: (context) => Ticket()),
                          );
                        },
                        child: const SizedBox(
                          width: 98,
                          child: Text(
                            'Attendees',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 12,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w700,
                              height: 1,
                            ),
                          ),
                        ),
                      ),
                    ),
                  const Positioned(
                    left: 74,
                    top: 323,
                    child: SizedBox(
                      width: 98,
                      child: Text(
                        'Profile',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 12,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w700,
                          height: 1,
                        ),
                      ),
                    ),
                  ),
                    Positioned(
                    left: 74,
                    top: 415,
                    child: GestureDetector(
                      onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => Login()),
                      );
                      },
                      child: const SizedBox(
                      width: 98,
                      child: Text(
                        'LogOut',
                        style: TextStyle(
                        color: Colors.black,
                        fontSize: 12,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w700,
                        height: 1,
                        ),
                      ),
                      ),
                    ),
                    ),
                  Positioned(
                    left: 23,
                    top: 178,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: const BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage("assets/Events.png"),
                          fit: BoxFit.contain,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 23,
                    top: 224,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: const BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage("assets/Events.png"),
                          fit: BoxFit.contain,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 23,
                    top: 270,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: const BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage("assets/People.png"),
                          fit: BoxFit.contain,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 23,
                    top: 316,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: const BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage("assets/Profile.png"),
                          fit: BoxFit.contain,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 23,
                    top: 408,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: const BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage("assets/Logout.png"),
                          fit: BoxFit.contain,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 84,
                    top: 23,
                    child: Container(
                      width: 88,
                      height: 87,
                      decoration: const ShapeDecoration(
                        color: Color(0xFFD9D9D9),
                        shape: OvalBorder(),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 91,
                    top: 30,
                    child: Container(
                      width: 74,
                      height: 74,
                      decoration: const BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage("assets/User.png"),
                          fit: BoxFit.contain,
                        ),
                      ),
                    ),
                  ),
                  const Positioned(
                    left: 91,
                    top: 115,
                    child: Text(
                      'Parody',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w700,
                        height: 1,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      body: ListView(
        children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 27,
                top: 119,
                child: Container(
                  width: 307,
                  height: 602,
                  decoration: const BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 27,
                top: 10,
                child: Container(
                  width: 307,
                  height: 602,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                    shadows: [
                      const BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 1,
                      ),
                      const BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 6,
                        offset: Offset(0, 4),
                        spreadRadius: -1,
                      ),
                      const BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 4,
                        offset: Offset(0, 2),
                        spreadRadius: -2,
                      )
                    ],
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: double.infinity,
                        height: 72,
                        clipBehavior: Clip.antiAlias,
                        decoration: const BoxDecoration(color: Color(0xFFF1F5F9)),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Expanded(
                              child: Container(
                                height: 73,
                                padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                clipBehavior: Clip.antiAlias,
                                decoration: const BoxDecoration(
                                  border: Border(
                                    left: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    top: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    right: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    bottom: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                  ),
                                ),
                                child: const Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    SizedBox(
                                      width: 65,
                                      height: 57,
                                      child: Text(
                                        'Email Address',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w700,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                height: 72,
                                padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                clipBehavior: Clip.antiAlias,
                                decoration: const BoxDecoration(
                                  border: Border(
                                    left: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    top: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    right: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    bottom: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                  ),
                                ),
                                child: const Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    SizedBox(
                                      width: 45,
                                      child: Text(
                                        'Ticket',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w700,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                height: 80,
                                padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                clipBehavior: Clip.antiAlias,
                                decoration: const BoxDecoration(
                                  border: Border(
                                    left: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    top: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    right: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    bottom: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                  ),
                                ),
                                child: const Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    SizedBox(
                                      width: 60,
                                      height: 48,
                                      child: Text(
                                        'Amount ',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w700,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Expanded(
                              child: Container(
                                height: 47,
                                padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                clipBehavior: Clip.antiAlias,
                                decoration: const BoxDecoration(
                                  border: Border(
                                    left: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    top: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    right: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                    bottom: BorderSide(
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Color(0xFFCBD5E1),
                                    ),
                                  ),
                                ),
                                child: const Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    SizedBox(
                                      width: 46,
                                      child: Text(
                                        'Action',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w700,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        height: 490,
                        clipBehavior: Clip.antiAlias,
                        decoration: const BoxDecoration(color: Colors.white),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 62,
                              clipBehavior: Clip.antiAlias,
                              decoration: const BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 62,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 58,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              clipBehavior: Clip.antiAlias,
                              decoration: const BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              clipBehavior: Clip.antiAlias,
                              decoration: const BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              clipBehavior: Clip.antiAlias,
                              decoration: const BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              clipBehavior: Clip.antiAlias,
                              decoration: const BoxDecoration(
                                color: Colors.white,
                                border: Border(
                                  left: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  top: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  right: BorderSide(
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                  bottom: BorderSide(
                                    width: 1,
                                    strokeAlign: BorderSide.strokeAlignOutside,
                                    color: Color(0xFFCBD5E1),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 47,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 47,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 107,
                                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                                      clipBehavior: Clip.antiAlias,
                                      decoration: const BoxDecoration(
                                        border: Border(
                                          left: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          top: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          right: BorderSide(
                                            width: 1,
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                          bottom: BorderSide(
                                            strokeAlign: BorderSide.strokeAlignOutside,
                                            color: Color(0xFFCBD5E1),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
      ),
    );
  }
}